### ISSUE TITLE
Crash when changing background color

### ISSUE THREAD

**Issue by Trurl101** [libgdx/gdx-particle-editor#10]
When clicking on "background color" in prefs (running on M1 Mac):

```
2024-10-08 16:03:44.151 osascript[13759:359696] +[IMKClient subclass]: chose IMKClient_Legacy
com.ray3k.gdxparticleeditor.lwjgl3.Lwjgl3Launcher: Error while running application
java.lang.RuntimeException: Actor: PopColorPicker
|  Table
|  |  Label: CHOOSE COLOR
|  |  TextButton
|  |  |  Label: HSB
|  |  TextButton
|  |  |  Label: HSL
|  |
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.ray3k.stripe.PopColorPicker.updateColorDisplay(PopColorPicker.java:1645)
	at com.ray3k.stripe.PopColorPicker.show(PopColorPicker.java:1618)
	at com.ray3k.stripe.PopTable.show(PopTable.java:326)
	at com.ray3k.gdxparticleeditor.widgets.poptables.PopPreviewSettings.lambda$new$2(PopPreviewSettings.java:177)
	at com.ray3k.gdxparticleeditor.Listeners$3.clicked(Listeners.java:100)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:229)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.ray3k.gdxparticleeditor.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:20)
	at com.ray3k.gdxparticleeditor.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:12)
Caused by: java.lang.NullPointerException: Cannot invoke "com.badlogic.gdx.scenes.scene2d.ui.Image.setColor(com.badlogic.gdx.graphics.Color)" because "com.ray3k.gdxparticleeditor.widgets.panels.PreviewPanel.previewBackgroundImage" is null
	at com.ray3k.gdxparticleeditor.widgets.poptables.PopPreviewSettings$3.updated(PopPreviewSettings.java:167)
	at com.ray3k.stripe.PopColorPicker$PopColorPickerListener.handle(PopColorPicker.java:2183)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188) 
```

**Comment by Mir1001** [comment]
I can confirm a bug also running on Windows (ver. 1.0.7).  Same error.
![image](https://github.com/user-attachments/assets/7ada5e41-08bd-4201-bfbf-c037bd729207)

**Comment by raeleus** [comment]
This will be resolved in the next version. Thanks folks!
